<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

/**
 * Artisan Command: Generate Permission Module
 *
 * Creates a new permission module file in config/permissions/
 *
 * Usage:
 *   php artisan make:permission-module {name}
 *   php artisan make:permission-module shipping
 *   php artisan make:permission-module price_groups
 *
 * @see config/permissions/README.md for module format documentation
 */
class MakePermissionModuleCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'make:permission-module
                            {name : The module name (lowercase, use underscores for multi-word)}
                            {--force : Overwrite existing module file}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new permission module in config/permissions/';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $name = $this->argument('name');

        // Validate name
        if (!preg_match('/^[a-z][a-z0-9_]*$/', $name)) {
            $this->error('Module name must be lowercase, start with a letter, and contain only letters, numbers, and underscores.');
            $this->line('Examples: products, price_groups, stock_locations');
            return self::FAILURE;
        }

        $path = config_path("permissions/{$name}.php");

        // Check if file exists
        if (File::exists($path) && !$this->option('force')) {
            $this->error("Permission module '{$name}' already exists at: {$path}");
            $this->line('Use --force to overwrite.');
            return self::FAILURE;
        }

        // Ensure directory exists
        $dir = dirname($path);
        if (!File::isDirectory($dir)) {
            File::makeDirectory($dir, 0755, true);
        }

        // Generate display name
        $displayName = Str::title(str_replace('_', ' ', $name));

        // Generate module content
        $content = $this->generateModuleContent($name, $displayName);

        // Write file
        File::put($path, $content);

        $this->info("Permission module created successfully: {$path}");
        $this->newLine();

        $this->line('Next steps:');
        $this->line('  1. Edit the module file to add your permissions');
        $this->line('  2. Run: php artisan db:seed --class=RolePermissionSeeder');
        $this->line('  3. Run: php artisan cache:clear');
        $this->newLine();

        $this->line('See config/permissions/README.md for documentation.');

        return self::SUCCESS;
    }

    /**
     * Generate module file content
     */
    protected function generateModuleContent(string $name, string $displayName): string
    {
        $order = $this->calculateNextOrder();

        return <<<PHP
<?php

/**
 * {$displayName} Permission Module
 *
 * Auto-generated by: php artisan make:permission-module {$name}
 *
 * @see config/permissions/README.md for documentation
 */

return [
    // =========================================================================
    // MODULE METADATA
    // =========================================================================

    'module' => '{$name}',
    'name' => '{$displayName}',
    'description' => 'Zarzadzanie: {$displayName}',
    'icon' => 'document',
    'order' => {$order},
    'color' => 'gray',

    // =========================================================================
    // PERMISSIONS
    // =========================================================================

    'permissions' => [
        'create' => [
            'name' => '{$name}.create',
            'label' => 'Tworzenie',
            'description' => 'Tworzenie nowych rekordow',
            'dangerous' => false,
        ],
        'read' => [
            'name' => '{$name}.read',
            'label' => 'Odczyt',
            'description' => 'Odczyt rekordow',
            'dangerous' => false,
        ],
        'update' => [
            'name' => '{$name}.update',
            'label' => 'Edycja',
            'description' => 'Edycja rekordow',
            'dangerous' => false,
        ],
        'delete' => [
            'name' => '{$name}.delete',
            'label' => 'Usuwanie',
            'description' => 'Usuwanie rekordow',
            'dangerous' => true,
        ],
    ],

    // =========================================================================
    // ROLE DEFAULTS
    // =========================================================================

    'role_defaults' => [
        'Admin' => ['create', 'read', 'update', 'delete'],
        'Manager' => ['create', 'read', 'update'],
        'Editor' => ['read', 'update'],
        'Warehouseman' => ['read'],
        'Salesperson' => ['read'],
        'Claims' => ['read'],
        'User' => ['read'],
    ],
];
PHP;
    }

    /**
     * Calculate next available order number
     */
    protected function calculateNextOrder(): int
    {
        $maxOrder = 100;

        $files = File::glob(config_path('permissions/*.php'));

        foreach ($files as $file) {
            $filename = basename($file, '.php');

            // Skip template files
            if (str_starts_with($filename, '_')) {
                continue;
            }

            try {
                $config = require $file;
                if (isset($config['order']) && $config['order'] >= $maxOrder) {
                    $maxOrder = $config['order'] + 10;
                }
            } catch (\Throwable $e) {
                // Ignore invalid files
            }
        }

        return $maxOrder;
    }
}
