<?php

namespace App\Http\Livewire\Admin\Compatibility;

use App\Models\Product;
use App\Models\VehicleModel;
use App\Services\CompatibilityManager;
use Illuminate\Support\Collection;
use Livewire\Attributes\Computed;
use Livewire\Component;

/**
 * BulkEditCompatibilityModal - Excel-inspired bulk compatibility editor
 *
 * FEATURES:
 * - Bidirectional mode: Part→Vehicle OR Vehicle→Part
 * - Multi-select search (checkboxes)
 * - Family helpers ("Select all YCF LITE*")
 * - Preview table with duplicate/conflict detection
 * - Transaction-safe bulk operations
 *
 * UX DESIGN:
 * - Excel horizontal drag: 1 part × 26 vehicles = 26 compatibilities
 * - Excel vertical drag: 50 parts × 1 vehicle = 50 compatibilities
 * - Family patterns: Group vehicles by brand prefix (YCF LITE*, KAYO TD*)
 * - Safety: Preview before apply, detect duplicates/conflicts
 *
 * LIVEWIRE 3.x COMPLIANCE:
 * - #[Computed] for expensive queries (selectedParts, vehicleFamilies)
 * - wire:key MANDATORY for multi-select checkboxes
 * - $dispatch() for events (not legacy emit())
 * - Alpine.js x-data for modal state
 *
 * BACKEND INTEGRATION:
 * - CompatibilityManager::bulkAddCompatibilities()
 * - CompatibilityManager::detectDuplicates()
 * - Transaction-safe with attempts: 5
 *
 * USAGE:
 * ```blade
 * @livewire('admin.compatibility.bulk-edit-compatibility-modal')
 * ```
 *
 * EVENTS:
 * - Listen: 'open-bulk-modal' (from CompatibilityManagement)
 * - Dispatch: 'bulk-edit-complete' (after successful apply)
 * - Dispatch: 'notify' (for user notifications)
 *
 * @package App\Http\Livewire\Admin\Compatibility
 * @version 1.0
 * @since ETAP_05d FAZA 2.2 (2025-10-24)
 */
class BulkEditCompatibilityModal extends Component
{
    /*
    |--------------------------------------------------------------------------
    | MODAL STATE
    |--------------------------------------------------------------------------
    */

    public bool $open = false;

    /*
    |--------------------------------------------------------------------------
    | DIRECTION (Part→Vehicle OR Vehicle→Part)
    |--------------------------------------------------------------------------
    */

    public string $direction = 'part_to_vehicle'; // or 'vehicle_to_part'

    /*
    |--------------------------------------------------------------------------
    | SELECTED ITEMS (from CompatibilityManagement table)
    |--------------------------------------------------------------------------
    */

    public array $selectedPartIds = [];
    public array $selectedVehicleIds = [];

    /*
    |--------------------------------------------------------------------------
    | SEARCH STATE
    |--------------------------------------------------------------------------
    */

    public string $searchQuery = '';
    public Collection $searchResults;
    public array $selectedTargetIds = []; // Multi-select from search results

    /*
    |--------------------------------------------------------------------------
    | COMPATIBILITY TYPE
    |--------------------------------------------------------------------------
    */

    public string $compatibilityType = 'original'; // or 'replacement'

    /*
    |--------------------------------------------------------------------------
    | PREVIEW STATE
    |--------------------------------------------------------------------------
    */

    public array $previewData = []; // Generated by detectDuplicates()
    public bool $showPreview = false;

    /*
    |--------------------------------------------------------------------------
    | UI STATE
    |--------------------------------------------------------------------------
    */

    public bool $isProcessing = false;
    public ?string $errorMessage = null;
    public ?string $successMessage = null;

    /*
    |--------------------------------------------------------------------------
    | DEPENDENCY INJECTION
    |--------------------------------------------------------------------------
    */

    protected CompatibilityManager $compatibilityManager;

    public function boot(CompatibilityManager $compatibilityManager)
    {
        $this->compatibilityManager = $compatibilityManager;
    }

    /*
    |--------------------------------------------------------------------------
    | LIFECYCLE
    |--------------------------------------------------------------------------
    */

    public function mount(): void
    {
        $this->searchResults = collect([]);
    }

    /*
    |--------------------------------------------------------------------------
    | MODAL CONTROL
    |--------------------------------------------------------------------------
    */

    /**
     * Open modal with selected items
     *
     * @param string $direction 'part_to_vehicle' or 'vehicle_to_part'
     * @param array $selectedIds Selected part IDs or vehicle IDs
     */
    public function openModal(string $direction, array $selectedIds): void
    {
        $this->direction = $direction;

        if ($direction === 'part_to_vehicle') {
            $this->selectedPartIds = $selectedIds;
            $this->selectedVehicleIds = [];
        } else {
            $this->selectedVehicleIds = $selectedIds;
            $this->selectedPartIds = [];
        }

        $this->reset(['searchQuery', 'selectedTargetIds', 'previewData', 'showPreview', 'errorMessage', 'successMessage']);
        $this->searchResults = collect([]);
        $this->open = true;
    }

    public function close(): void
    {
        $this->open = false;
        $this->reset();
    }

    /*
    |--------------------------------------------------------------------------
    | SEARCH
    |--------------------------------------------------------------------------
    */

    /**
     * Search for target items (vehicles OR parts based on direction)
     */
    public function search(): void
    {
        if (strlen($this->searchQuery) < 2) {
            $this->searchResults = collect([]);
            return;
        }

        if ($this->direction === 'part_to_vehicle') {
            // Search vehicles
            $this->searchResults = VehicleModel::query()
                ->where(function ($query) {
                    $query->where('sku', 'like', "%{$this->searchQuery}%")
                        ->orWhere('brand', 'like', "%{$this->searchQuery}%")
                        ->orWhere('model', 'like', "%{$this->searchQuery}%");
                })
                ->orderBy('brand')
                ->orderBy('model')
                ->limit(100)
                ->get();
        } else {
            // Search parts (products)
            $this->searchResults = Product::query()
                ->where('product_type', 'spare_part')
                ->where(function ($query) {
                    $query->where('sku', 'like', "%{$this->searchQuery}%")
                        ->orWhere('name', 'like', "%{$this->searchQuery}%");
                })
                ->orderBy('sku')
                ->limit(100)
                ->get();
        }
    }

    /**
     * Toggle target selection (multi-select checkbox)
     */
    public function toggleTarget(int $id): void
    {
        if (in_array($id, $this->selectedTargetIds)) {
            $this->selectedTargetIds = array_values(array_diff($this->selectedTargetIds, [$id]));
        } else {
            $this->selectedTargetIds[] = $id;
        }

        // Reset preview when selection changes
        $this->showPreview = false;
        $this->previewData = [];
    }

    /*
    |--------------------------------------------------------------------------
    | FAMILY HELPERS (Excel-inspired)
    |--------------------------------------------------------------------------
    */

    /**
     * Select all vehicles from a brand family (e.g., "YCF LITE*")
     */
    public function selectAllFamily(string $familyPrefix): void
    {
        if ($this->direction !== 'part_to_vehicle') {
            return;
        }

        $familyVehicles = $this->searchResults
            ->filter(fn($vehicle) => str_starts_with($vehicle->brand . ' ' . $vehicle->model, $familyPrefix))
            ->pluck('id')
            ->toArray();

        // Merge with existing selection (avoid duplicates)
        $this->selectedTargetIds = array_values(array_unique(array_merge($this->selectedTargetIds, $familyVehicles)));

        // Reset preview
        $this->showPreview = false;
        $this->previewData = [];
    }

    /*
    |--------------------------------------------------------------------------
    | PREVIEW
    |--------------------------------------------------------------------------
    */

    /**
     * Generate preview using CompatibilityManager::detectDuplicates()
     */
    public function generatePreview(): void
    {
        if (empty($this->selectedTargetIds)) {
            $this->dispatch('notify', message: 'Zaznacz przynajmniej 1 pozycję docelową', type: 'warning');
            return;
        }

        $this->isProcessing = true;
        $this->errorMessage = null;

        try {
            // Build combinations array for detectDuplicates()
            $combinations = [];

            if ($this->direction === 'part_to_vehicle') {
                // Part → Vehicle: selectedPartIds × selectedTargetIds (vehicles)
                foreach ($this->selectedPartIds as $partId) {
                    foreach ($this->selectedTargetIds as $vehicleId) {
                        $combinations[] = [
                            'part_id' => $partId,
                            'vehicle_id' => $vehicleId,
                            'attribute_code' => $this->compatibilityType,
                        ];
                    }
                }
            } else {
                // Vehicle → Part: selectedVehicleIds × selectedTargetIds (parts)
                foreach ($this->selectedVehicleIds as $vehicleId) {
                    foreach ($this->selectedTargetIds as $partId) {
                        $combinations[] = [
                            'part_id' => $partId,
                            'vehicle_id' => $vehicleId,
                            'attribute_code' => $this->compatibilityType,
                        ];
                    }
                }
            }

            // Detect duplicates using CompatibilityManager
            $detection = $this->compatibilityManager->detectDuplicates($combinations);

            // Calculate NEW entries (total - duplicates - conflicts)
            $newCount = count($combinations) - count($detection['duplicates']) - count($detection['conflicts']);

            $this->previewData = [
                'new' => array_slice(array_diff_key($combinations, array_flip(array_keys($detection['duplicates']))), 0, $newCount),
                'duplicates' => $detection['duplicates'],
                'conflicts' => $detection['conflicts'],
            ];

            $this->showPreview = true;

        } catch (\Exception $e) {
            $this->errorMessage = "Błąd generowania podglądu: {$e->getMessage()}";
        } finally {
            $this->isProcessing = false;
        }
    }

    /*
    |--------------------------------------------------------------------------
    | APPLY
    |--------------------------------------------------------------------------
    */

    /**
     * Apply bulk operation using CompatibilityManager::bulkAddCompatibilities()
     */
    public function apply(): void
    {
        if (!$this->showPreview) {
            $this->dispatch('notify', message: 'Najpierw wygeneruj podgląd', type: 'warning');
            return;
        }

        $this->isProcessing = true;
        $this->errorMessage = null;
        $this->successMessage = null;

        try {
            $partIds = [];
            $vehicleIds = [];

            if ($this->direction === 'part_to_vehicle') {
                $partIds = $this->selectedPartIds;
                $vehicleIds = $this->selectedTargetIds;
            } else {
                $partIds = $this->selectedTargetIds;
                $vehicleIds = $this->selectedVehicleIds;
            }

            // Call CompatibilityManager::bulkAddCompatibilities()
            $result = $this->compatibilityManager->bulkAddCompatibilities(
                $partIds,
                $vehicleIds,
                $this->compatibilityType,
                3 // sourceId: 3 = manual entry
            );

            if (!empty($result['errors'])) {
                $this->errorMessage = implode(', ', $result['errors']);
                return;
            }

            $this->successMessage = "Sukces! Utworzono {$result['created']} dopasowań. Pominięto {$result['duplicates']} duplikatów.";

            // Dispatch event to parent component
            $this->dispatch('bulk-edit-complete', [
                'created' => $result['created'],
                'duplicates' => $result['duplicates'],
            ]);

            // Close modal after 2 seconds
            $this->dispatch('notify', message: $this->successMessage, type: 'success');

            // Reset and close
            $this->reset();
            $this->open = false;

        } catch (\Exception $e) {
            $this->errorMessage = "Błąd zastosowania zmian: {$e->getMessage()}";
        } finally {
            $this->isProcessing = false;
        }
    }

    /*
    |--------------------------------------------------------------------------
    | COMPUTED PROPERTIES (Livewire 3.x #[Computed])
    |--------------------------------------------------------------------------
    */

    /**
     * Get selected parts with full data (cached)
     */
    #[Computed]
    public function selectedParts(): Collection
    {
        if (empty($this->selectedPartIds)) {
            return collect([]);
        }

        return Product::whereIn('id', $this->selectedPartIds)
            ->select('id', 'sku', 'name')
            ->get();
    }

    /**
     * Get selected vehicles with full data (cached)
     */
    #[Computed]
    public function selectedVehicles(): Collection
    {
        if (empty($this->selectedVehicleIds)) {
            return collect([]);
        }

        return VehicleModel::whereIn('id', $this->selectedVehicleIds)
            ->select('id', 'sku', 'brand', 'model')
            ->get();
    }

    /**
     * Group vehicles by brand family prefix (cached)
     * Example: "YCF LITE" → [YCF LITE 88S, YCF LITE 125, ...]
     */
    #[Computed]
    public function vehicleFamilies(): array
    {
        if ($this->searchResults->isEmpty()) {
            return [];
        }

        $families = [];

        foreach ($this->searchResults as $vehicle) {
            // Extract family prefix (first 2 words of brand + model)
            $fullName = $vehicle->brand . ' ' . $vehicle->model;
            $words = explode(' ', $fullName);
            $familyPrefix = implode(' ', array_slice($words, 0, min(2, count($words))));

            if (!isset($families[$familyPrefix])) {
                $families[$familyPrefix] = [];
            }

            $families[$familyPrefix][] = $vehicle;
        }

        return $families;
    }

    /*
    |--------------------------------------------------------------------------
    | RENDER
    |--------------------------------------------------------------------------
    */

    public function render()
    {
        return view('livewire.admin.compatibility.bulk-edit-compatibility-modal');
    }
}
