<?php

namespace App\Services\Export\Generators;

use App\Models\ExportProfile;
use Illuminate\Support\Facades\Log;
use RuntimeException;
use XMLWriter;

/**
 * XML Google Shopping Feed Generator
 *
 * Generates Google Merchant Center RSS 2.0 (Atom) feed with:
 * - g:namespace for Google Shopping fields
 * - XMLWriter for memory-efficient streaming
 * - Defensive field handling (skips empty/null values)
 * - HTML tag stripping for descriptions
 * - Proper XML character escaping
 */
class XmlGoogleShoppingGenerator implements FeedGeneratorInterface
{
    private const GOOGLE_NS = 'http://base.google.com/ns/1.0';
    private const CHANNEL_TITLE = 'PPM Product Feed';
    private const CHANNEL_LINK = 'https://ppm.mpptrade.pl';
    private const CHANNEL_DESCRIPTION = 'Product feed generated by PPM';
    private const DEFAULT_CONDITION = 'new';
    private const DEFAULT_CURRENCY = 'PLN';

    public function generate(array $products, ExportProfile $profile): string
    {
        $dir = storage_path('app/exports/feeds');
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $filename = $profile->slug . '-' . now()->format('Ymd-His') . '.xml';
        $filePath = $dir . DIRECTORY_SEPARATOR . $filename;

        $xml = new XMLWriter();
        if (!$xml->openUri($filePath)) {
            throw new RuntimeException("Cannot open file for writing: {$filePath}");
        }

        try {
            $this->writeDocument($xml, $products, $profile);
        } finally {
            $xml->flush();
        }

        Log::info('XmlGoogleShoppingGenerator: Feed generated', [
            'profile_id' => $profile->id,
            'profile_slug' => $profile->slug,
            'product_count' => count($products),
            'file_size' => filesize($filePath),
        ]);

        return $filePath;
    }

    public function getContentType(): string
    {
        return 'application/xml; charset=UTF-8';
    }

    public function getFileExtension(): string
    {
        return 'xml';
    }

    /**
     * Write complete XML document structure.
     */
    private function writeDocument(XMLWriter $xml, array $products, ExportProfile $profile): void
    {
        $xml->startDocument('1.0', 'UTF-8');
        $xml->setIndent(true);
        $xml->setIndentString('  ');

        // <rss xmlns:g="..." version="2.0">
        $xml->startElement('rss');
        $xml->writeAttribute('xmlns:g', self::GOOGLE_NS);
        $xml->writeAttribute('version', '2.0');

        // <channel>
        $xml->startElement('channel');
        $xml->writeElement('title', self::CHANNEL_TITLE);
        $xml->writeElement('link', self::CHANNEL_LINK);
        $xml->writeElement('description', self::CHANNEL_DESCRIPTION);

        foreach ($products as $product) {
            $this->writeItem($xml, $product);
        }

        $xml->endElement(); // </channel>
        $xml->endElement(); // </rss>
        $xml->endDocument();
    }

    /**
     * Write single <item> element with Google Shopping fields.
     */
    private function writeItem(XMLWriter $xml, array $product): void
    {
        $xml->startElement('item');

        // g:id - SKU (required)
        $this->writeGoogleElement($xml, 'id', $product['sku'] ?? null);

        // g:title - Product name (required)
        $this->writeGoogleElement($xml, 'title', $product['name'] ?? null);

        // g:description - strip HTML tags
        $description = $this->resolveDescription($product);
        $this->writeGoogleElement($xml, 'description', $description);

        // g:link - product URL if available
        $this->writeGoogleElement($xml, 'link', $product['product_url'] ?? null);

        // g:image_link - main image
        $this->writeGoogleElement($xml, 'image_link', $product['image_url_main'] ?? null);

        // g:additional_image_link - extra images
        $this->writeAdditionalImages($xml, $product);

        // g:price - first available gross price + currency
        $price = $this->resolvePrice($product);
        $this->writeGoogleElement($xml, 'price', $price);

        // g:sale_price - not in flat data currently, reserved for future
        // Sale prices would require separate field mapping

        // g:availability - mapped from stock
        $availability = $this->resolveAvailability($product);
        $this->writeGoogleElement($xml, 'availability', $availability);

        // g:brand - manufacturer
        $this->writeGoogleElement($xml, 'brand', $product['manufacturer'] ?? null);

        // g:gtin - EAN
        $this->writeGoogleElement($xml, 'gtin', $product['ean'] ?? null);

        // g:mpn - SKU as manufacturer part number
        $this->writeGoogleElement($xml, 'mpn', $product['sku'] ?? null);

        // g:condition - always new
        $this->writeGoogleElement($xml, 'condition', self::DEFAULT_CONDITION);

        // g:product_type - category path
        $categoryPath = $this->formatCategoryPath($product['category_path'] ?? null);
        $this->writeGoogleElement($xml, 'product_type', $categoryPath);

        // g:shipping_weight - weight in kg
        $weight = $this->formatWeight($product['weight'] ?? null);
        $this->writeGoogleElement($xml, 'shipping_weight', $weight);

        $xml->endElement(); // </item>
    }

    /**
     * Write a Google namespace element. Skips if value is null or empty string.
     */
    private function writeGoogleElement(XMLWriter $xml, string $name, ?string $value): void
    {
        if ($value === null || $value === '') {
            return;
        }

        $xml->startElementNs('g', $name, null);
        $xml->text($value);
        $xml->endElement();
    }

    /**
     * Resolve product description from short or long description, strip HTML.
     */
    private function resolveDescription(array $product): ?string
    {
        $description = $product['short_description'] ?? $product['long_description'] ?? null;

        if ($description === null || $description === '') {
            return null;
        }

        // Strip HTML tags and decode entities
        $clean = strip_tags((string) $description);
        $clean = html_entity_decode($clean, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        $clean = trim(preg_replace('/\s+/', ' ', $clean));

        // Google Shopping description limit: 5000 characters
        if (mb_strlen($clean) > 5000) {
            $clean = mb_substr($clean, 0, 4997) . '...';
        }

        return $clean !== '' ? $clean : null;
    }

    /**
     * Write additional image links from image_urls_all field.
     *
     * Google Shopping allows up to 10 additional images.
     */
    private function writeAdditionalImages(XMLWriter $xml, array $product): void
    {
        $allImages = $product['image_urls_all'] ?? null;

        if ($allImages === null || $allImages === '') {
            return;
        }

        // image_urls_all is a pipe-separated string from ProductExportService
        $urls = is_array($allImages)
            ? $allImages
            : array_map('trim', explode('|', (string) $allImages));

        $mainImage = $product['image_url_main'] ?? null;
        $count = 0;

        foreach ($urls as $url) {
            $url = trim($url);

            // Skip empty, skip main image (already in g:image_link)
            if ($url === '' || $url === $mainImage) {
                continue;
            }

            // Google allows max 10 additional images
            if ($count >= 10) {
                break;
            }

            $this->writeGoogleElement($xml, 'additional_image_link', $url);
            $count++;
        }
    }

    /**
     * Resolve first available gross price from product data.
     *
     * Searches for any field matching price_gross_* pattern and returns
     * the first non-null value formatted with currency.
     */
    private function resolvePrice(array $product): ?string
    {
        foreach ($product as $key => $value) {
            if (str_starts_with($key, 'price_gross_') && $value !== null && $value !== '') {
                $numericValue = (float) $value;
                if ($numericValue > 0) {
                    return number_format($numericValue, 2, '.', '') . ' ' . self::DEFAULT_CURRENCY;
                }
            }
        }

        return null;
    }

    /**
     * Resolve availability from stock fields.
     *
     * Returns 'in_stock' if any stock_* field has quantity > 0,
     * otherwise 'out_of_stock'.
     */
    private function resolveAvailability(array $product): string
    {
        foreach ($product as $key => $value) {
            if (str_starts_with($key, 'stock_') && $value !== null) {
                if ((int) $value > 0) {
                    return 'in_stock';
                }
            }
        }

        return 'out_of_stock';
    }

    /**
     * Format category path for Google product_type.
     *
     * Converts pipe-separated paths to " > " Google format.
     * Uses first path if multiple categories exist.
     */
    private function formatCategoryPath(?string $categoryPath): ?string
    {
        if ($categoryPath === null || $categoryPath === '') {
            return null;
        }

        // ProductExportService joins multiple categories with ' | '
        // Google expects single path, take the first one
        $paths = explode(' | ', $categoryPath);
        $firstPath = trim($paths[0]);

        if ($firstPath === '') {
            return null;
        }

        // If path already uses " > " separator, return as-is
        if (str_contains($firstPath, ' > ')) {
            return $firstPath;
        }

        // If path uses " / " or "/" separator, convert to " > "
        if (str_contains($firstPath, '/')) {
            return implode(' > ', array_map('trim', explode('/', $firstPath)));
        }

        return $firstPath;
    }

    /**
     * Format weight value with kg unit.
     */
    private function formatWeight(mixed $weight): ?string
    {
        if ($weight === null || $weight === '') {
            return null;
        }

        $numericWeight = (float) $weight;

        if ($numericWeight <= 0) {
            return null;
        }

        return number_format($numericWeight, 2, '.', '') . ' kg';
    }
}
