<?php

namespace App\Services\VisualEditor\Blocks\Content;

use App\Services\VisualEditor\Blocks\BaseBlock;

/**
 * Merit List Block - Icon + Heading + Text list.
 *
 * REFACTORED for CSS-First Architecture (UVE v2.3):
 * - ZERO inline styles
 * - Uses data attributes for JS initialization
 * - CSS rules generated by CssRuleGenerator
 * - Property Panel controls edit CSS, NOT inline styles
 */
class MeritListBlock extends BaseBlock
{
    public string $type = 'merit-list';
    public string $name = 'Lista zalet';
    public string $icon = 'heroicons-check-badge';
    public string $category = 'content';

    public array $defaultSettings = [
        'layout' => 'vertical', // vertical, horizontal, grid
        'columns' => 2,
        'icon_type' => 'checkmark', // checkmark, number, custom
        'icon_color' => 'var(--pd-primary-color)',
        'icon_size' => '1.5rem',
        'spacing' => '1.5rem',
        'show_divider' => false,
    ];

    /**
     * ETAP_07h PP.3: Property Panel controls for MeritListBlock.
     *
     * CSS-First: kontrolki edytuja CSS rules, NIE inline styles!
     * - root: list-settings, layout (dla calej listy)
     * - .pd-merit-list__list: grid/flex layout
     * - .pd-merit-list__item: kazdy element osobno
     * - .pd-merit-list__icon: kolor i rozmiar ikony (CSS, nie inline!)
     * - teksty: typography TYLKO na elementach tekstowych
     */
    public array $propertyPanelControls = [
        'root' => ['list-settings', 'box-model', 'background'],
        '.pd-merit-list__title' => ['typography', 'color-picker', 'box-model'],
        '.pd-merit-list__list' => ['layout-grid', 'layout-flex', 'box-model'],
        '.pd-merit-list__item' => ['box-model', 'background', 'border'],
        '.pd-merit-list__icon' => ['color-picker', 'size'],
        '.pd-merit-list__heading' => ['typography', 'color-picker'],
        '.pd-merit-list__text' => ['typography', 'color-picker'],
    ];

    /**
     * Built-in icon SVGs.
     */
    private array $builtInIcons = [
        'checkmark' => '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>',
        'star' => '<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>',
        'arrow' => '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6" /></svg>',
    ];

    /**
     * Render merit list block - CSS-First compliant.
     *
     * ZASADA: Brak inline styles! Wszystkie style przez CSS classes.
     * - Unikalna klasa per blok: uve-meritlist-{hash}
     * - Data attributes dla CSS generation (columns, spacing, etc.)
     * - CSS rules generowane przez CssRuleGenerator
     */
    public function render(array $content, array $settings, array $children = []): string
    {
        $settings = $this->mergeSettings($settings);

        $items = $content['items'] ?? [];
        $title = $this->escape($content['title'] ?? '');

        // Generate unique class for this block instance (CSS-First)
        $uniqueClass = $this->generateUniqueClass($content, $settings);

        // Container classes - NO inline styles!
        $containerClasses = $this->classNames([
            'pd-block',
            'pd-merit-list',
            $uniqueClass,
            "pd-merit-list--{$settings['layout']}",
        ]);

        // Data attributes for CSS generation (NOT inline styles)
        $dataAttrs = implode(' ', [
            "data-layout=\"{$settings['layout']}\"",
            "data-columns=\"{$settings['columns']}\"",
            "data-spacing=\"{$settings['spacing']}\"",
            "data-icon-color=\"{$settings['icon_color']}\"",
            "data-icon-size=\"{$settings['icon_size']}\"",
        ]);

        // Title HTML
        $titleHtml = '';
        if ($title) {
            $titleHtml = "<h3 class=\"pd-merit-list__title\">{$title}</h3>";
        }

        // Build items - NO inline styles!
        $itemsHtml = $this->buildItemsHtml($items, $settings);

        return <<<HTML
        <div class="{$containerClasses}" {$dataAttrs}>
            {$titleHtml}
            <ul class="pd-merit-list__list">
                {$itemsHtml}
            </ul>
        </div>
        HTML;
    }

    /**
     * Build list items HTML - CSS-First compliant (NO inline styles!).
     */
    private function buildItemsHtml(array $items, array $settings): string
    {
        $html = '';

        foreach ($items as $index => $item) {
            $heading = $this->escape($item['heading'] ?? '');
            $text = $item['text'] ?? ''; // May contain HTML
            $customIcon = $item['icon'] ?? '';

            // Build icon
            $iconHtml = $this->buildIconHtml($settings, $index + 1, $customIcon);

            // Divider
            $dividerClass = $settings['show_divider'] ? 'pd-merit-list__item--divider' : '';

            // NO inline styles! CSS handles icon color/size via .pd-merit-list__icon class
            $html .= <<<HTML
            <li class="pd-merit-list__item {$dividerClass}">
                <div class="pd-merit-list__icon">
                    {$iconHtml}
                </div>
                <div class="pd-merit-list__content">
                    <h4 class="pd-merit-list__heading">{$heading}</h4>
                    <div class="pd-merit-list__text">{$text}</div>
                </div>
            </li>
            HTML;
        }

        return $html;
    }

    /**
     * Build icon HTML based on type.
     */
    private function buildIconHtml(array $settings, int $number, string $customIcon): string
    {
        $iconType = $settings['icon_type'];

        if ($iconType === 'number') {
            return "<span class=\"pd-merit-list__number\">{$number}</span>";
        }

        if ($iconType === 'custom' && $customIcon) {
            return $customIcon;
        }

        // Built-in icon
        return $this->builtInIcons[$iconType] ?? $this->builtInIcons['checkmark'];
    }

    /**
     * Generate unique CSS class for this block instance.
     *
     * CSS-First: klasa generowana z settings, umozliwia reuse CSS rules.
     */
    private function generateUniqueClass(array $content, array $settings): string
    {
        $hashData = [
            'layout' => $settings['layout'],
            'columns' => $settings['columns'],
            'spacing' => $settings['spacing'],
            'icon_color' => $settings['icon_color'],
            'icon_size' => $settings['icon_size'],
        ];
        ksort($hashData);
        $hash = substr(md5(json_encode($hashData)), 0, 8);

        return "uve-meritlist-{$hash}";
    }

    /**
     * Get CSS rules for this block (used by CssRuleGenerator).
     *
     * CSS-First: te rules sa zapisywane do custom.css, NIE jako inline styles!
     */
    public function getCssRules(array $content, array $settings): array
    {
        $settings = $this->mergeSettings($settings);
        $uniqueClass = $this->generateUniqueClass($content, $settings);

        $rules = [];

        // List container styles based on layout
        if ($settings['layout'] === 'grid') {
            $rules[".{$uniqueClass} .pd-merit-list__list"] = [
                'display' => 'grid',
                'grid-template-columns' => "repeat({$settings['columns']}, 1fr)",
                'gap' => $settings['spacing'],
            ];
        } else {
            $rules[".{$uniqueClass} .pd-merit-list__list"] = [
                'gap' => $settings['spacing'],
            ];
        }

        // Icon styles (color and size via CSS, not inline!)
        $rules[".{$uniqueClass} .pd-merit-list__icon"] = [
            'color' => $settings['icon_color'],
            'font-size' => $settings['icon_size'],
        ];

        return $rules;
    }

    public function getSchema(): array
    {
        return [
            'content' => [
                'title' => [
                    'type' => 'text',
                    'label' => 'Tytul listy',
                    'required' => false,
                ],
                'items' => [
                    'type' => 'repeater',
                    'label' => 'Elementy',
                    'fields' => [
                        'heading' => [
                            'type' => 'text',
                            'label' => 'Naglowek',
                        ],
                        'text' => [
                            'type' => 'richtext',
                            'label' => 'Tekst',
                        ],
                        'icon' => [
                            'type' => 'icon',
                            'label' => 'Ikona (opcjonalna)',
                        ],
                    ],
                ],
            ],
            'settings' => [
                'layout' => [
                    'type' => 'select',
                    'label' => 'Uklad',
                    'options' => [
                        'vertical' => 'Pionowy',
                        'horizontal' => 'Poziomy',
                        'grid' => 'Siatka',
                    ],
                    'default' => 'vertical',
                ],
                'columns' => [
                    'type' => 'number',
                    'label' => 'Liczba kolumn',
                    'min' => 1,
                    'max' => 4,
                    'default' => 2,
                    'condition' => ['layout' => 'grid'],
                ],
                'icon_type' => [
                    'type' => 'select',
                    'label' => 'Typ ikony',
                    'options' => [
                        'checkmark' => 'Ptaszek',
                        'star' => 'Gwiazdka',
                        'arrow' => 'Strzalka',
                        'number' => 'Numeracja',
                        'custom' => 'Wlasna',
                    ],
                    'default' => 'checkmark',
                ],
                'icon_color' => [
                    'type' => 'color',
                    'label' => 'Kolor ikony',
                    'default' => 'var(--pd-primary-color)',
                ],
                'icon_size' => [
                    'type' => 'text',
                    'label' => 'Rozmiar ikony',
                    'default' => '1.5rem',
                ],
                'spacing' => [
                    'type' => 'text',
                    'label' => 'Odstepy',
                    'default' => '1.5rem',
                ],
                'show_divider' => [
                    'type' => 'boolean',
                    'label' => 'Pokaz separator',
                    'default' => false,
                ],
            ],
        ];
    }
}
