<?php

namespace App\Services\VisualEditor\Blocks\Media;

use App\Services\VisualEditor\Blocks\BaseBlock;

/**
 * Parallax Image Block - Image with parallax scroll effect.
 *
 * REFACTORED for CSS-First Architecture (UVE v2.3):
 * - ZERO inline styles
 * - Uses data attributes for JS initialization
 * - CSS rules generated by CssRuleGenerator
 * - Property Panel controls edit CSS, NOT inline styles
 */
class ParallaxImageBlock extends BaseBlock
{
    public string $type = 'parallax-image';
    public string $name = 'Obraz z efektem parallax';
    public string $icon = 'heroicons-arrows-up-down';
    public string $category = 'media';

    /**
     * ETAP_07h PP.3: Property Panel controls for ParallaxImageBlock.
     *
     * CSS-First: kontrolki edytuja CSS rules, NIE inline styles!
     * - root: rozmiar i parallax-settings (min-height, background-attachment)
     * - .pd-parallax: background-image picker (KRYTYCZNE!)
     * - .pd-parallax__overlay: overlay background i efekty
     * - teksty: typography TYLKO na elementach tekstowych
     */
    public array $propertyPanelControls = [
        'root' => ['size', 'box-model'],
        '.pd-parallax' => ['background', 'parallax-settings'],
        '.pd-parallax__overlay' => ['background', 'effects'],
        '.pd-parallax__content' => ['layout-flex', 'box-model'],
        '.pd-parallax__title' => ['typography', 'color-picker', 'box-model'],
        '.pd-parallax__subtitle' => ['typography', 'color-picker'],
    ];

    public array $defaultSettings = [
        'height' => '400px',
        'speed' => 0.5, // 0.1 to 1.0
        'overlay' => false,
        'overlay_color' => '#000000',
        'overlay_opacity' => 0.3,
        'mobile_fallback' => 'fixed', // fixed, scroll, hidden
        'background_position' => 'center center',
    ];

    /**
     * Render parallax block - CSS-First compliant.
     *
     * ZASADA: Brak inline styles! Wszystkie style przez CSS classes.
     * - Unikalna klasa per blok: uve-parallax-{hash}
     * - Data attributes dla JS (parallax speed, image URL)
     * - CSS rules generowane przez CssRuleGenerator
     */
    public function render(array $content, array $settings, array $children = []): string
    {
        $settings = $this->mergeSettings($settings);

        $image = $this->escape($content['image'] ?? '');
        $title = $this->escape($content['title'] ?? '');
        $subtitle = $this->escape($content['subtitle'] ?? '');

        if (!$image) {
            return '<!-- Parallax image: no image provided -->';
        }

        // Generate unique class for this block instance (CSS-First)
        $uniqueClass = $this->generateUniqueClass($content, $settings);

        // Container classes - NO inline styles!
        $containerClasses = $this->classNames([
            'pd-block',
            'pd-parallax',
            $uniqueClass,
            "pd-parallax--mobile-{$settings['mobile_fallback']}",
        ]);

        // Data attributes for JS initialization and CSS generation
        // These are READ by JavaScript and CssRuleGenerator, NOT inline styles
        $dataAttrs = implode(' ', [
            "data-parallax-speed=\"{$settings['speed']}\"",
            "data-bg-image=\"{$image}\"",
            "data-bg-position=\"{$settings['background_position']}\"",
            "data-height=\"{$settings['height']}\"",
        ]);

        // Overlay HTML - NO inline styles!
        $overlayHtml = '';
        if ($settings['overlay']) {
            $overlayDataAttrs = implode(' ', [
                "data-overlay-color=\"{$settings['overlay_color']}\"",
                "data-overlay-opacity=\"{$settings['overlay_opacity']}\"",
            ]);
            $overlayHtml = "<div class=\"pd-parallax__overlay\" {$overlayDataAttrs}></div>";
        }

        // Content HTML
        $contentHtml = '';
        if ($title || $subtitle) {
            $contentHtml = <<<HTML
            <div class="pd-parallax__content">
                <h2 class="pd-parallax__title">{$title}</h2>
                <p class="pd-parallax__subtitle">{$subtitle}</p>
            </div>
            HTML;
        }

        return <<<HTML
        <div class="{$containerClasses}" {$dataAttrs}>
            {$overlayHtml}
            {$contentHtml}
        </div>
        HTML;
    }

    /**
     * Generate unique CSS class for this block instance.
     *
     * CSS-First: klasa generowana z contentu, umozliwia reuse CSS rules.
     */
    private function generateUniqueClass(array $content, array $settings): string
    {
        $hashData = [
            'image' => $content['image'] ?? '',
            'height' => $settings['height'],
            'bg_position' => $settings['background_position'],
            'overlay' => $settings['overlay'],
            'overlay_color' => $settings['overlay_color'],
            'overlay_opacity' => $settings['overlay_opacity'],
        ];
        ksort($hashData);
        $hash = substr(md5(json_encode($hashData)), 0, 8);

        return "uve-parallax-{$hash}";
    }

    /**
     * Get CSS rules for this block (used by CssRuleGenerator).
     *
     * CSS-First: te rules sa zapisywane do custom.css, NIE jako inline styles!
     */
    public function getCssRules(array $content, array $settings): array
    {
        $settings = $this->mergeSettings($settings);
        $uniqueClass = $this->generateUniqueClass($content, $settings);
        $image = $content['image'] ?? '';

        $rules = [];

        // Main parallax container styles
        $rules[".{$uniqueClass}"] = [
            'min-height' => $settings['height'],
            'background-image' => $image ? "url('{$image}')" : 'none',
            'background-position' => $settings['background_position'],
            'background-attachment' => 'fixed',
            'background-size' => 'cover',
        ];

        // Overlay styles (if enabled)
        if ($settings['overlay']) {
            $rgb = sscanf($settings['overlay_color'], "#%02x%02x%02x");
            if ($rgb && count($rgb) === 3) {
                $rules[".{$uniqueClass} .pd-parallax__overlay"] = [
                    'background' => "rgba({$rgb[0]}, {$rgb[1]}, {$rgb[2]}, {$settings['overlay_opacity']})",
                ];
            }
        }

        return $rules;
    }

    public function getSchema(): array
    {
        return [
            'content' => [
                'image' => [
                    'type' => 'image',
                    'label' => 'Obraz',
                    'required' => true,
                ],
                'title' => [
                    'type' => 'text',
                    'label' => 'Tytul (opcjonalny)',
                    'required' => false,
                ],
                'subtitle' => [
                    'type' => 'text',
                    'label' => 'Podtytul (opcjonalny)',
                    'required' => false,
                ],
            ],
            'settings' => [
                'height' => [
                    'type' => 'text',
                    'label' => 'Wysokosc',
                    'default' => '400px',
                ],
                'speed' => [
                    'type' => 'range',
                    'label' => 'Szybkosc efektu',
                    'min' => 0.1,
                    'max' => 1.0,
                    'step' => 0.1,
                    'default' => 0.5,
                ],
                'overlay' => [
                    'type' => 'boolean',
                    'label' => 'Nakladka',
                    'default' => false,
                ],
                'overlay_color' => [
                    'type' => 'color',
                    'label' => 'Kolor nakladki',
                    'default' => '#000000',
                    'condition' => ['overlay' => true],
                ],
                'overlay_opacity' => [
                    'type' => 'range',
                    'label' => 'Przezroczystosc',
                    'min' => 0,
                    'max' => 1,
                    'step' => 0.1,
                    'default' => 0.3,
                    'condition' => ['overlay' => true],
                ],
                'mobile_fallback' => [
                    'type' => 'select',
                    'label' => 'Zachowanie na mobile',
                    'options' => [
                        'fixed' => 'Statyczny obraz',
                        'scroll' => 'Przewijanie',
                        'hidden' => 'Ukryty',
                    ],
                    'default' => 'fixed',
                ],
                'background_position' => [
                    'type' => 'select',
                    'label' => 'Pozycja obrazu',
                    'options' => [
                        'center center' => 'Srodek',
                        'center top' => 'Gora',
                        'center bottom' => 'Dol',
                        'left center' => 'Lewa',
                        'right center' => 'Prawa',
                    ],
                    'default' => 'center center',
                ],
            ],
        ];
    }
}
