<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Cache;

class SmartVehicleAlias extends Model
{
    use HasFactory;

    protected $fillable = [
        'vehicle_product_id',
        'alias',
        'alias_normalized',
        'alias_type',
        'is_auto_generated',
        'is_active',
        'created_by',
    ];

    protected $casts = [
        'vehicle_product_id' => 'integer',
        'is_auto_generated' => 'boolean',
        'is_active' => 'boolean',
    ];

    protected static function boot(): void
    {
        parent::boot();

        static::saving(function (self $model) {
            $model->alias_normalized = mb_strtolower(trim($model->alias));
        });

        static::saved(function (self $model) {
            Cache::forget("smart_aliases_vehicle_{$model->vehicle_product_id}");
        });

        static::deleted(function (self $model) {
            Cache::forget("smart_aliases_vehicle_{$model->vehicle_product_id}");
        });
    }

    public function vehicleProduct(): BelongsTo
    {
        return $this->belongsTo(Product::class, 'vehicle_product_id');
    }

    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    public function scopeManual($query)
    {
        return $query->where('is_auto_generated', false);
    }

    public function scopeForVehicle($query, int $vehicleId)
    {
        return $query->where('vehicle_product_id', $vehicleId);
    }
}
